// <auto-generated />
using System;
using MAVN.Service.Credentials.MsSqlRepositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.Credentials.MsSqlRepositories.Migrations
{
    [DbContext(typeof(CredentialsContext))]
    [Migration("20200701065307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("credentials")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.Credentials.MsSqlRepositories.Entities.AdminCredentialsEntity", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnName("login")
                        .HasColumnType("text");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnName("admin_id")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt")
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("admin_credentials");
                });

            modelBuilder.Entity("MAVN.Service.Credentials.MsSqlRepositories.Entities.CustomerCredentialsEntity", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnName("login")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt")
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("customer_credentials");
                });

            modelBuilder.Entity("MAVN.Service.Credentials.MsSqlRepositories.Entities.PartnerCredentialsEntity", b =>
                {
                    b.Property<string>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("partner_id")
                        .HasColumnType("text")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnName("client_id")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt")
                        .HasColumnType("text");

                    b.HasKey("PartnerId");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("partner_credentials");
                });

            modelBuilder.Entity("MAVN.Service.Credentials.MsSqlRepositories.Entities.PasswordResetEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnName("expires_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnName("identifier")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("password_reset");
                });

            modelBuilder.Entity("MAVN.Service.Credentials.MsSqlRepositories.Entities.PinCodeEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_pin_codes");
                });

            modelBuilder.Entity("MAVN.Service.Credentials.MsSqlRepositories.Entities.PinCodeEntity", b =>
                {
                    b.HasOne("MAVN.Service.Credentials.MsSqlRepositories.Entities.CustomerCredentialsEntity", null)
                        .WithOne("PinCode")
                        .HasForeignKey("MAVN.Service.Credentials.MsSqlRepositories.Entities.PinCodeEntity", "CustomerId")
                        .HasPrincipalKey("MAVN.Service.Credentials.MsSqlRepositories.Entities.CustomerCredentialsEntity", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
